theme = "dracula-purple"
# icons = "nerdfonts"

[editor]
rulers = [120]
shell = ["zsh", "-c"]
true-color = true
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.statusline]
left = ["mode", "spinner", "spacer", "file-name"]
center = []
right = ["diagnostics", "selections", "position", "position-percentage", "separator", "file-encoding", "file-line-ending", "file-type", "separator", "spacer", "version-control", "spacer"]
separator = " â”‚"

[editor.lsp]
auto-signature-help = true
display-inlay-hints = true

[editor.indent-guides]
render = true
rainbow = "dim"

[keys.normal]
C-j = "half_page_down"
C-k = "half_page_up"
